<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <ProjectReference Include="..\..\src\FunctionFoundry.Storage\FunctionFoundry.Storage.csproj" />
  </ItemGroup>

</Project>
